version: "3.8"

services:
    musician:
        container_name: musician
        image: nashrull/helloworld:latest
        restart: always 
        tty: false
        ports:
            - 3001:3000
            